### PR TITLE
UnraveledMC Config Updates

### PR DESCRIPTION
**Pull request by Superior-tL**
This is a small update.

> Better UI for the config = easy to use.

> Updated headers

> Updated all .yml files

> Ready to compile no errors!

### CODE REVIEW

**Comment by aggelosQQ** [comment]
Looks pretty good!

**Comment by CreeperSeth** [comment]
Not to me, @aggelosQQ please don't merge anything without my approval

**Comment by CreeperSeth** [comment]
This fucks my entire system up

**Comment by FoxIshDaBest** [comment]
This grammar is sad tbh.

**Pull request merged**
